const DB_NAME='pillplan-next-db';
const DB_VERSION=1;
let db; let view='today'; let period=7;
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=e=>{const d=e.target.result;if(!d.objectStoreNames.contains('meds'))d.createObjectStore('meds',{keyPath:'id'});if(!d.objectStoreNames.contains('events')){const s=d.createObjectStore('events',{keyPath:'eventId'});s.createIndex('slot','slot',{unique:false});s.createIndex('createdAt','createdAt',{unique:false});}if(!d.objectStoreNames.contains('meta'))d.createObjectStore('meta',{keyPath:'key'});};r.onsuccess=()=>{db=r.result;resolve(db)};r.onerror=()=>reject(r.error);});}
function tx(store,mode='readonly'){return db.transaction(store,mode).objectStore(store)}
function all(store){return new Promise((res,rej)=>{const r=tx(store).getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)})}
function getOne(store,key){return new Promise((res,rej)=>{const r=tx(store).get(key);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function put(store,obj){return new Promise((res,rej)=>{const r=tx(store,'readwrite').put(obj);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function clear(store){return new Promise((res,rej)=>{const r=tx(store,'readwrite').clear();r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function del(store,key){return new Promise((res,rej)=>{const r=tx(store,'readwrite').delete(key);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function localDate(d=new Date()){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`}
function today(){return localDate()}
function slotKey(mid,date,time){return `${date}_${mid}_${time}`}
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random()}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function fmtDate(ds=today()){return new Date(ds+'T12:00:00').toLocaleDateString('de-DE',{weekday:'long',day:'numeric',month:'long'})}
async function latestEvents(){const ev=await all('events');ev.sort((a,b)=>String(a.createdAt).localeCompare(String(b.createdAt)));const map={};for(const e of ev)map[e.slot]=e;return map}
function tierForLegacy(v){if(v===true)return 'unrated';if(v===false||v==null)return null;if(typeof v==='object'){if(v.taken===false)return null;return v.tier||'unrated'}return null}
async function importBackup(file){const text=await file.text();let obj=JSON.parse(text),state=obj;if(obj.localStorage&&obj.localStorage.pillplan_v4)state=typeof obj.localStorage.pillplan_v4==='string'?JSON.parse(obj.localStorage.pillplan_v4):obj.localStorage.pillplan_v4;if(!state||!Array.isArray(state.meds)||typeof state.taken!=='object')throw new Error('Ungültige PillPlan-Sicherung');await clear('meds');await clear('events');for(const m of state.meds)await put('meds',{id:m.id,name:m.name,times:m.times||[],color:m.color||'#2a7c74',startDate:m.startDate||null,scheduleHistory:m.scheduleHistory||[]});for(const [slot,val] of Object.entries(state.taken||{})){const tier=tierForLegacy(val);if(!tier)continue;await put('events',{eventId:uid(),slot,type:'taken',tier,createdAt:(val&&val.takenAt)||new Date().toISOString(),legacy:true});}await put('meta',{key:'importedAt',value:new Date().toISOString()});await render()}
async function exportBackup(){const meds=await all('meds'),events=await all('events'),meta=await all('meta');const blob=new Blob([JSON.stringify({schema:'pillplan-next-v3',exportedAt:new Date().toISOString(),meds,events,meta},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`PillPlan_Backup_${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function computeTier(time,now=new Date()){const [h,m]=time.split(':').map(Number),diff=now.getHours()*60+now.getMinutes()-(h*60+m);return diff>=45?'red':diff>=30?'yellow':'green'}
async function toggle(mid,date,time,forceTier=null){const slot=slotKey(mid,date,time),map=await latestEvents(),current=map[slot];const turningOn=!(current&&current.type==='taken');const tier=turningOn?(forceTier||computeTier(time)):'unrated';await put('events',{eventId:uid(),slot,type:turningOn?'taken':'undo',tier,createdAt:new Date().toISOString()});await render()}
async function addMed(name,time,color='#2a7c74'){if(!name||!time)return;await put('meds',{id:Date.now(),name:name.trim(),times:[time],color,startDate:today(),scheduleHistory:[{from:today(),times:[time]}]});view='today';await render()}
async function editMed(id){const m=await getOne('meds',id);if(!m)return;const name=prompt('Medikament bearbeiten – Name',m.name);if(name===null)return;const time=prompt('Einnahmezeit (HH:MM)',m.times?.[0]||'08:00');if(time===null)return;if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(time)){alert('Bitte Uhrzeit als HH:MM eingeben.');return}m.name=name.trim()||m.name;m.times=[time];m.scheduleHistory=[...(m.scheduleHistory||[]),{from:today(),times:[time]}];await put('meds',m);await render()}
async function removeMed(id){const m=await getOne('meds',id);if(!m)return;if(!confirm(`${m.name} wirklich entfernen? Die Historie bleibt im Ereignisprotokoll erhalten.`))return;await del('meds',id);await render()}
function pastDays(n){const out=[];for(let i=n-1;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);out.push(localDate(d))}return out}
async function todayStats(){const meds=await all('meds'),map=await latestEvents(),td=today();let tot=0,done=0,onTime=0,rated=0;for(const m of meds)for(const t of m.times){tot++;const e=map[slotKey(m.id,td,t)];if(e&&e.type==='taken'){done++;if(e.tier!=='unrated'){rated++;if(e.tier==='green')onTime++;}}}return{tot,done,pct:tot?Math.round(done/tot*100):0,punct:rated?Math.round(onTime/rated*100):0}}
async function streak(){const meds=await all('meds'),map=await latestEvents();if(!meds.length)return 0;let s=0;for(let i=0;i<365;i++){const d=new Date();d.setDate(d.getDate()-i);const ds=localDate(d);let due=0,ok=true;for(const m of meds){if(m.startDate&&ds<m.startDate)continue;for(const t of m.times){due++;const e=map[slotKey(m.id,ds,t)];if(!(e&&e.type==='taken'))ok=false}}if(due===0)continue;if(ok)s++;else if(i>0)break;else break;}return s}
function classifyDay(m,d,map){let due=0,done=0,worst='green';if(m.startDate&&d<m.startDate)return 'pre';for(const t of m.times){due++;const e=map[slotKey(m.id,d,t)];if(e&&e.type==='taken'){done++;if(e.tier==='red')worst='red';else if(e.tier==='yellow'&&worst!=='red')worst='yellow';else if(e.tier==='unrated'&&worst==='green')worst='unrated'}}if(!due)return 'pre';if(done===0)return '';if(done<due)return 'partial';return worst}
async function periodStats(){const meds=await all('meds'),map=await latestEvents(),days=pastDays(period);let due=0,done=0;for(const d of days)for(const m of meds){if(m.startDate&&d<m.startDate)continue;for(const t of m.times){due++;const e=map[slotKey(m.id,d,t)];if(e&&e.type==='taken')done++;}}return{due,done,pct:due?Math.round(done/due*100):0}}
function statusText(e){if(!e||e.type!=='taken')return 'Offen';if(e.tier==='red')return 'Dokumentiert · stark verspätet';if(e.tier==='yellow')return 'Dokumentiert · verspätet';if(e.tier==='unrated')return 'Dokumentiert · Zeit unbekannt';return 'Dokumentiert · pünktlich'}
function tierClass(e){return e&&e.type==='taken'?(e.tier==='yellow'?'yellow':e.tier==='red'?'red':'green'):''}
async function render(){const app=document.getElementById('app'),meds=await all('meds'),map=await latestEvents(),s=await todayStats(),st=await streak(),ps=await periodStats(),td=today();let title=view==='plan'?'Dokumentation':'Heute';let html=`<div class="header-row"><div class="logo">Pill<span>Plan</span></div><div class="date-chip">${fmtDate()}</div></div><div class="progress-card"><div class="ring">${s.pct}%</div><div><div class="progress-title">${title}</div><div class="progress-sub">${s.done} / ${s.tot} dokumentiert</div><div class="punct">Pünktlichkeit: ${s.punct}%</div><div class="streak">🔥 ${st} ${st===1?'Tag':'Tage'} in Folge</div></div></div><select class="period-select" id="period"><option value="7" ${period===7?'selected':''}>1 Woche</option><option value="14" ${period===14?'selected':''}>2 Wochen</option><option value="30" ${period===30?'selected':''}>1 Monat</option></select><div class="tabs"><button class="tab ${view==='today'?'active':''}" data-v="today">💊 Heute</button><button class="tab ${view==='plan'?'active':''}" data-v="plan">📅 Plan</button><button class="tab ${view==='add'?'active':''}" data-v="add">＋ Hinzufügen</button></div><main class="content">`;
if(view==='today'){
 if(!meds.length)html+=`<div class="empty">Noch keine Medikamente. Über „Hinzufügen“ kannst du starten oder unter Einstellungen eine Sicherung importieren.</div>`;
 for(const m of meds)for(const t of m.times){const e=map[slotKey(m.id,td,t)],on=e&&e.type==='taken',cls=tierClass(e);html+=`<div class="card dose"><div class="dose-icon">${on?'✅':'💊'}</div><div class="grow"><div class="name">${esc(m.name)}</div><div class="time">${esc(t)}</div><div class="statusline ${cls}">${statusText(e)}</div></div><button class="check ${on?'on':''}" data-toggle="${m.id}" data-time="${esc(t)}">${on?'✓':'○'}</button></div>`}
}
if(view==='plan'){
 html+=`<div class="legend"><div>Was bedeuten die Farben?</div><div class="legend-row"><span class="sw g">✓</span> Grün – dokumentiert und pünktlich</div><div class="legend-row"><span class="sw y">!</span> Gelb – 30–44 Min. verspätet</div><div class="legend-row"><span class="sw r">!</span> Rot – 45+ Min. verspätet</div><div class="legend-row"><span class="sw n">✓</span> Hellgrau – nachgetragen, genaue Zeit unbekannt</div></div><div class="section-label">${period===7?'1 WOCHE':period===14?'2 WOCHEN':'1 MONAT'} · ${ps.done}/${ps.due} · ${ps.pct}%</div>`;const days=pastDays(period);
 for(const m of meds){html+=`<div class="plan-med"><div class="plan-head"><div><div class="plan-name">${esc(m.name)}</div><div class="small">${m.times.join(' · ')}</div></div><div class="med-actions"><button class="mini" data-edit="${m.id}">✏️ Bearbeiten</button><button class="mini remove" data-remove="${m.id}">Entfernen</button></div></div><div class="days">`;for(const d of days){const cls=classifyDay(m,d,map),dt=new Date(d+'T12:00:00'),visual=cls==='unrated'?'':cls==='partial'?'yellow':cls==='pre'?'':cls,mark=cls==='pre'?'·':cls?'✓':'○';html+=`<button class="day ${visual} ${d===td?'today':''}" data-day="${d}" data-mid="${m.id}" title="Nachtragen / ändern"><div>${dt.toLocaleDateString('de-DE',{weekday:'short'}).slice(0,2)}</div><strong>${dt.getDate()}</strong><div>${mark}</div></button>`}html+=`</div></div>`}
}
if(view==='add')html+=`<div class="card"><div class="form-title">Medikament hinzufügen</div><input id="med-name" class="field" placeholder="Name des Medikaments"><input id="med-time" class="field" type="time" value="08:00"><button id="add-med" class="btn primary">Hinzufügen</button></div>`;
if(view==='settings')html+=`<div class="card"><div class="form-title">Einstellungen</div><div class="settings-row"><strong>Daten & Sicherung</strong><div class="small">Verlauf wird in IndexedDB gespeichert.</div><input id="backup-file" class="field" type="file" accept="application/json,.json"><button id="import-btn" class="btn primary">Backup importieren</button><button id="export-btn" class="btn secondary">Backup exportieren</button></div><div class="settings-row"><strong>Statistik</strong><div class="metric"><span>Zeitraum</span><strong>${period===7?'1 Woche':period===14?'2 Wochen':'1 Monat'}</strong></div><div class="metric"><span>Dokumentiert</span><strong>${ps.done}/${ps.due}</strong></div><div class="metric"><span>Quote</span><strong>${ps.pct}%</strong></div></div><div class="settings-row"><strong>System</strong><div class="small">PillPlan Next · stabiler Verlaufskern · keine Demo-Daten</div></div></div>`;
html+=`</main><nav class="bottom-nav"><button class="nav ${view==='today'?'active':''}" data-v="today"><span class="nav-icon">💊</span>HEUTE</button><button class="nav ${view==='plan'?'active':''}" data-v="plan"><span class="nav-icon">📅</span>PLAN</button><button class="nav ${view==='add'?'active':''}" data-v="add"><span class="nav-icon">＋</span>HINZUFÜGEN</button><button class="nav ${view==='settings'?'active':''}" data-v="settings"><span class="nav-icon">⚙️</span>EINSTELLUNGEN</button></nav>`;app.innerHTML=html;
document.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{view=b.dataset.v;render()});document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>toggle(Number(b.dataset.toggle),td,b.dataset.time));document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editMed(Number(b.dataset.edit)));document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>removeMed(Number(b.dataset.remove)));document.querySelectorAll('[data-day]').forEach(b=>b.onclick=async()=>{const m=await getOne('meds',Number(b.dataset.mid));if(!m||!m.times?.length)return;await toggle(m.id,b.dataset.day,m.times[0],'unrated')});const p=document.getElementById('period');if(p)p.onchange=()=>{period=Number(p.value);render()};const add=document.getElementById('add-med');if(add)add.onclick=()=>addMed(document.getElementById('med-name').value,document.getElementById('med-time').value);const imp=document.getElementById('import-btn');if(imp)imp.onclick=async()=>{try{const f=document.getElementById('backup-file').files[0];if(!f)throw new Error('Bitte Backup-Datei auswählen');await importBackup(f);alert('Import erfolgreich');}catch(e){alert(e.message)}};const exp=document.getElementById('export-btn');if(exp)exp.onclick=exportBackup;}
(async()=>{await openDB();if('serviceWorker'in navigator)navigator.serviceWorker.register('/pillplan-next/sw.js',{scope:'/pillplan-next/'}).catch(()=>{});await render();})();