const {test,expect}=require('@playwright/test');
test('real browser smoke: document, correction, report, backup safety, offline',async({page,context})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 page.on('dialog',d=>d.accept('2'));
 await page.goto('http://127.0.0.1:8765/pillplan-next/');
 await expect(page.locator('#app .bottom-nav')).toBeVisible();
 await page.locator('[data-v="add"]').click();
 await page.locator('#med-name').fill('Synthetic QA Pill');
 await page.locator('#med-dose').fill('5 mg');
 await page.locator('#add-med').click();
 await expect(page.locator('.dose-name').filter({hasText:'Synthetic QA Pill'})).toBeVisible();
 await page.locator('[data-toggle]').first().click();
 await expect(page.locator('.dose-status').first()).toContainText(/Dokumentiert|Documented/);
 await page.reload();
 await expect(page.locator('.dose-status').first()).toContainText(/Dokumentiert|Documented/);
 await page.locator('[data-toggle]').first().click();
 await expect(page.locator('.dose-status').first()).not.toContainText(/Dokumentiert|Documented/);
 await page.locator('[data-v="settings"]').click();
 await page.locator('#report-btn').click();
 await expect(page.locator('#pp-modal')).toBeVisible();
 await expect(page.locator('#pp-modal')).toContainText('Synthetic QA Pill');
 await page.locator('#pp-report-close').click();
 const before=await page.evaluate(async()=>{const db=await new Promise((ok,no)=>{const r=indexedDB.open('pillplan-next-db');r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)});return new Promise((ok,no)=>{const tx=db.transaction('meds');const r=tx.objectStore('meds').getAll();r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})});
 expect(before.some(m=>m.name==='Synthetic QA Pill')).toBeTruthy();
 await page.locator('#backup-file').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({meds:[{id:1,name:'Corrupt',times:['99:99']}],events:[]}))});
 await page.locator('#import-btn').click();
 const after=await page.evaluate(async()=>{const db=await new Promise((ok,no)=>{const r=indexedDB.open('pillplan-next-db');r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)});return new Promise((ok,no)=>{const tx=db.transaction('meds');const r=tx.objectStore('meds').getAll();r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})});
 expect(after).toEqual(before);
 await page.reload();
 await context.setOffline(true);
 await page.reload();
 await expect(page.locator('.bottom-nav')).toBeVisible();
 await expect(page.locator('.dose-name').filter({hasText:'Synthetic QA Pill'})).toBeVisible();
 await context.setOffline(false);
 expect(errors).toEqual([]);
});

test('extended browser: edit, valid backup roundtrip, report print and end',async({page})=>{
 page.on('dialog',d=>d.accept('1'));
 await page.goto('http://127.0.0.1:8765/pillplan-next/');
 await page.locator('[data-v="add"]').click();
 await page.locator('#med-name').fill('QA Roundtrip');
 await page.locator('#add-med').click();
 console.log('EXTENDED_STAGE_1');
 await page.locator('[data-v="plan"]').click();
 await page.locator('details.med-menu summary').first().click();
 await page.locator('[data-edit]').first().click();
 await page.locator('#pp-edit-name').fill('QA Roundtrip Edited');
 console.log('EXTENDED_STAGE_2');
 await page.locator('#pp-edit-save').click();
 await expect(page.locator('body')).toContainText('QA Roundtrip Edited');
 await page.locator('[data-v="settings"]').click();
 const downloadPromise=page.waitForEvent('download');
 console.log('EXTENDED_STAGE_3');
 await page.locator('#export-btn').click();
 console.log('EXTENDED_STAGE_4');
 const download=await downloadPromise;
 const p=await download.path();
 const fs=require('node:fs');
 const backup=JSON.parse(fs.readFileSync(p,'utf8'));
 expect(backup.meds.some(x=>x.name==='QA Roundtrip Edited')).toBeTruthy();
 await page.locator('#backup-file').setInputFiles({name:'valid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});
 console.log('EXTENDED_STAGE_5');
 await page.locator('#import-btn').click();
 await page.reload();
 await page.locator('[data-v="plan"]').click();
 await expect(page.locator('body')).toContainText('QA Roundtrip Edited');
 await page.locator('[data-v="settings"]').click();
 console.log('EXTENDED_STAGE_6');
 await page.locator('#report-btn').click();
 const popupPromise=page.waitForEvent('popup');
 console.log('EXTENDED_STAGE_7');
 await page.locator('#pp-report-print').click();
 console.log('EXTENDED_STAGE_8');
 const popup=await popupPromise;
 await popup.waitForLoadState('domcontentloaded');
 const reportText=await popup.locator('body').innerText();
 expect(reportText).toContain('QA Roundtrip Edited');
 const pdf=await popup.pdf({format:'A4'});
 expect(pdf.length).toBeGreaterThan(1000);
 await popup.close();
 await page.locator('#pp-report-close').click();
 await page.locator('[data-v="plan"]').click();
 console.log('EXTENDED_STAGE_9');
 await page.locator('details.med-menu summary').first().click();
 await page.locator('[data-end]').first().click();
 await expect(page.locator('body')).toContainText(/Beendet|Ended/);
});
