const {test,expect}=require('@playwright/test');
test('real browser smoke: document, correction, report, backup safety, offline',async({page,context})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 page.on('dialog',d=>d.accept('2'));
 await page.goto('http://127.0.0.1:8765/pillplan-next/');
 await expect(page.locator('#app .bottom-nav')).toBeVisible();
 await page.locator('[data-v="add"]').click();
 await page.locator('#med-name').fill('Synthetic QA Pill');
 await page.locator('#med-dose').fill('5 mg');
 await page.locator('#add-med').click();
 await expect(page.locator('.dose-name').filter({hasText:'Synthetic QA Pill'})).toBeVisible();
 await page.locator('[data-toggle]').first().click();
 await expect(page.locator('.dose-status').first()).toContainText('Dokumentiert');
 await page.reload();
 await expect(page.locator('.dose-status').first()).toContainText('Dokumentiert');
 await page.locator('[data-toggle]').first().click();
 await expect(page.locator('.dose-status').first()).not.toContainText('Dokumentiert');
 await page.locator('[data-v="settings"]').click();
 await page.locator('#report-btn').click();
 await expect(page.locator('#pp-modal')).toBeVisible();
 await expect(page.locator('#pp-modal')).toContainText('Synthetic QA Pill');
 await page.locator('#pp-report-close').click();
 const before=await page.evaluate(async()=>{const db=await new Promise((ok,no)=>{const r=indexedDB.open('pillplan-next-db');r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)});return new Promise((ok,no)=>{const tx=db.transaction('meds');const r=tx.objectStore('meds').getAll();r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})});
 expect(before.some(m=>m.name==='Synthetic QA Pill')).toBeTruthy();
 await page.locator('#backup-file').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({meds:[{id:1,name:'Corrupt',times:['99:99']}],events:[]}))});
 await page.locator('#import-btn').click();
 const after=await page.evaluate(async()=>{const db=await new Promise((ok,no)=>{const r=indexedDB.open('pillplan-next-db');r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)});return new Promise((ok,no)=>{const tx=db.transaction('meds');const r=tx.objectStore('meds').getAll();r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})});
 expect(after).toEqual(before);
 await page.reload();
 await context.setOffline(true);
 await page.reload();
 await expect(page.locator('.bottom-nav')).toBeVisible();
 await expect(page.locator('.dose-name').filter({hasText:'Synthetic QA Pill'})).toBeVisible();
 await context.setOffline(false);
 expect(errors).toEqual([]);
});
