/* PillPlan Next consolidated runtime v1 */
'use strict';
const DB_NAME='pillplan-next-db', DB_VERSION=1;
let db, view='today', period=7;

function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=e=>{const d=e.target.result;if(!d.objectStoreNames.contains('meds'))d.createObjectStore('meds',{keyPath:'id'});if(!d.objectStoreNames.contains('events')){const s=d.createObjectStore('events',{keyPath:'eventId'});s.createIndex('slot','slot',{unique:false});s.createIndex('createdAt','createdAt',{unique:false});}if(!d.objectStoreNames.contains('meta'))d.createObjectStore('meta',{keyPath:'key'});};r.onsuccess=()=>{db=r.result;resolve(db)};r.onerror=()=>reject(r.error);});}
function tx(s,m='readonly'){return db.transaction(s,m).objectStore(s)}
function all(s){return new Promise((res,rej)=>{const r=tx(s).getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)})}
function getOne(s,k){return new Promise((res,rej)=>{const r=tx(s).get(k);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function put(s,o){return new Promise((res,rej)=>{const r=tx(s,'readwrite').put(o);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function clear(s){return new Promise((res,rej)=>{const r=tx(s,'readwrite').clear();r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random()}
function localDate(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function today(){return localDate()}
function addDays(ds,n){const d=new Date(ds+'T12:00:00');d.setDate(d.getDate()+n);return localDate(d)}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function fmtDate(ds=today()){return new Date(ds+'T12:00:00').toLocaleDateString('de-DE',{weekday:'long',day:'numeric',month:'long'})}
function normalizeTimes(a){return [...new Set((a||[]).filter(Boolean))].sort()}
function slotKey(mid,date,time){return `${date}_${mid}_${time}`}
function pastDays(n){const o=[];for(let i=n-1;i>=0;i--)o.push(addDays(today(),-i));return o}
async function latestEvents(){const ev=await all('events');ev.sort((a,b)=>String(a.createdAt).localeCompare(String(b.createdAt)));const m={};for(const e of ev)m[e.slot]=e;return m}
function timesForDate(m,ds){if(!m)return[];if(m.startDate&&ds<m.startDate)return[];if(m.endDate&&ds>m.endDate)return[];const h=(m.scheduleHistory||[]).filter(x=>x&&x.from&&Array.isArray(x.times)).slice().sort((a,b)=>a.from.localeCompare(b.from));let t=null;for(const x of h){if(x.from<=ds)t=x.times;else break}return normalizeTimes(t===null?(m.times||[]):t)}
function upsertSchedule(m,from,times){const h=(m.scheduleHistory||[]).slice(),i=h.findIndex(x=>x.from===from),e={from,times:normalizeTimes(times)};if(i>=0)h[i]=e;else h.push(e);h.sort((a,b)=>a.from.localeCompare(b.from));m.scheduleHistory=h}
function computeTier(time,now=new Date()){const [h,m]=time.split(':').map(Number),diff=now.getHours()*60+now.getMinutes()-(h*60+m);return diff>=45?'red':diff>=30?'yellow':'green'}
function tierClass(e){return e&&e.type==='taken'?(e.tier==='yellow'?'yellow':e.tier==='red'?'red':e.tier==='unrated'?'unrated':'green'):''}
function statusText(e){if(!e||e.type!=='taken')return'Offen';if(e.tier==='red')return'Dokumentiert · stark verspätet';if(e.tier==='yellow')return'Dokumentiert · verspätet';if(e.tier==='unrated')return'Dokumentiert · Zeit unbekannt';return'Dokumentiert · pünktlich'}
async function toggle(mid,date,time,forced=null){const map=await latestEvents(),slot=slotKey(mid,date,time),cur=map[slot],on=!(cur&&cur.type==='taken');if(!on){const med=await getOne('meds',mid);if(!confirm(`${med?.name||'Diese Einnahme'} am ${new Date(date+'T12:00:00').toLocaleDateString('de-DE')} um ${time} wurde bereits dokumentiert.\n\nEintrag wirklich zurücknehmen?`))return}await put('events',{eventId:uid(),slot,type:on?'taken':'undo',tier:on?(forced||computeTier(time)):'unrated',createdAt:new Date().toISOString()});await render()}
async function todayStats(){const meds=await all('meds'),map=await latestEvents();let tot=0,done=0,rated=0,onTime=0;for(const m of meds)for(const t of timesForDate(m,today())){tot++;const e=map[slotKey(m.id,today(),t)];if(e&&e.type==='taken'){done++;if(e.tier!=='unrated'){rated++;if(e.tier==='green')onTime++}}}return{tot,done,pct:tot?Math.round(done/tot*100):0,punct:rated?Math.round(onTime/rated*100):0}}
async function streak(){const meds=await all('meds'),map=await latestEvents();let s=0;for(let i=0;i<365;i++){const ds=addDays(today(),-i);let due=0,ok=true;for(const m of meds)for(const t of timesForDate(m,ds)){due++;const e=map[slotKey(m.id,ds,t)];if(!(e&&e.type==='taken'))ok=false}if(!due)continue;if(ok)s++;else break}return s}
function classifyDay(m,d,map){const ts=timesForDate(m,d);if(!ts.length)return'pre';let done=0,worst='green';for(const t of ts){const e=map[slotKey(m.id,d,t)];if(e&&e.type==='taken'){done++;if(e.tier==='red')worst='red';else if(e.tier==='yellow'&&worst!=='red')worst='yellow';else if(e.tier==='unrated'&&worst==='green')worst='unrated'}}if(!done)return'';if(done<ts.length)return'partial';return worst}
async function periodStats(){const meds=await all('meds'),map=await latestEvents();let due=0,done=0;for(const d of pastDays(period))for(const m of meds)for(const t of timesForDate(m,d)){due++;const e=map[slotKey(m.id,d,t)];if(e&&e.type==='taken')done++}return{due,done,pct:due?Math.round(done/due*100):0}}
function praise(s,st){if(!s.tot)return'';if(!s.done)return'Guten Morgen. Dein erster Check wartet.';if(s.done<s.tot)return`${s.done} von ${s.tot} geschafft. Du bleibst dran.`;if(st>=30)return'30 Tage in Folge. Sehr stark – diese Routine trägt.';if(st>=14)return'Zwei Wochen konsequent. Stark weitergemacht.';if(st>=7)return'Eine Woche. Stark.';if(st>=3)return`${st} Tage in Folge. Gute Routine.`;return`${s.done} von ${s.tot}. Du bleibst dran — das zählt.`}
function timeRowsHTML(times=['08:00']){return normalizeTimes(times).map((t,i)=>`<div class="time-row"><input class="field med-time" type="time" value="${esc(t)}"><button type="button" class="time-remove" ${i===0&&times.length===1?'disabled':''}>−</button></div>`).join('')}
function collectTimes(){return normalizeTimes([...document.querySelectorAll('.med-time')].map(x=>x.value))}
function bindTimeRows(){document.querySelectorAll('.time-remove').forEach(b=>b.onclick=()=>{if(document.querySelectorAll('.time-row').length>1)b.closest('.time-row').remove()})}
async function addMed(){const name=document.getElementById('med-name')?.value.trim(),times=collectTimes();if(!name)return alert('Bitte Medikamentenname eingeben.');if(!times.length)return alert('Bitte mindestens eine Einnahmezeit angeben.');await put('meds',{id:Date.now(),name,times,color:document.getElementById('med-color')?.value||'#2a7c74',dose:(document.getElementById('med-dose')?.value||'').trim(),doctorInstructions:(document.getElementById('doctor-instructions')?.value||'').trim(),expiryDate:document.getElementById('med-expiry')?.value||'',startDate:today(),scheduleHistory:[{from:today(),times:[...times]}]});view='today';await render()}
async function editMed(id){const m=await getOne('meds',id);if(!m||m.endDate)return;const name=prompt('Medikament bearbeiten – Name',m.name);if(name===null)return;const raw=prompt('Einnahmezeiten, durch Komma getrennt',timesForDate(m,today()).join(', '));if(raw===null)return;const nt=normalizeTimes(raw.split(',').map(x=>x.trim()));if(!nt.length)return;const dose=prompt('Dosis / Stärke',m.dose||'');if(dose===null)return;const instr=prompt('Ärztliche Einnahmevorgabe',m.doctorInstructions||'');if(instr===null)return;const exp=prompt('MHD / Verfallsdatum (JJJJ-MM-TT)',m.expiryDate||'');if(exp===null)return;m.name=name.trim()||m.name;m.dose=dose.trim();m.doctorInstructions=instr.trim();m.expiryDate=exp;const old=timesForDate(m,today());if(JSON.stringify(old)!==JSON.stringify(nt)){let from=today();const map=await latestEvents();if(old.some(t=>map[slotKey(m.id,today(),t)]?.type==='taken'))from=addDays(today(),1);upsertSchedule(m,from,nt);m.times=nt}await put('meds',m);await render()}
async function endMed(id){const m=await getOne('meds',id);if(!m||m.endDate)return;if(!confirm(`${m.name} wirklich beenden? Die bisherige Historie bleibt erhalten.`))return;const from=addDays(today(),1);upsertSchedule(m,from,[]);m.endDate=today();m.endedAt=new Date().toISOString();m.times=[];await put('meds',m);await render()}
async function chooseHistorical(m,date){const ts=timesForDate(m,date);if(!ts.length)return alert('Für diesen Tag war keine Einnahme geplant.');if(ts.length===1)return toggle(m.id,date,ts[0],'unrated');const ans=prompt(`Welche Einnahme ändern?\n${ts.map((t,i)=>`${i+1}: ${t}`).join('\n')}`);const i=Number(ans)-1;if(Number.isInteger(i)&&i>=0&&i<ts.length)await toggle(m.id,date,ts[i],'unrated')}
async function exportBackup(){const payload={schema:'pillplan-next-consolidated-v1',exportedAt:new Date().toISOString(),meds:await all('meds'),events:await all('events'),meta:await all('meta')};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`PillPlan_Backup_${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function importBackup(file){const obj=JSON.parse(await file.text());if(!obj||!Array.isArray(obj.meds)||!Array.isArray(obj.events))throw new Error('Keine gültige PillPlan-Next-Sicherung');await clear('meds');await clear('events');await clear('meta');for(const m of obj.meds)await put('meds',m);for(const e of obj.events)await put('events',e);for(const x of obj.meta||[])await put('meta',x);await render()}
async function buildStats(n=30){const meds=await all('meds'),map=await latestEvents();const o={green:0,yellow:0,red:0,unrated:0,undocumented:0,due:0,done:0};for(const d of pastDays(n))for(const m of meds)for(const t of timesForDate(m,d)){o.due++;const e=map[slotKey(m.id,d,t)];if(!e||e.type!=='taken'){o.undocumented++;continue}o.done++;if(e.tier==='yellow')o.yellow++;else if(e.tier==='red')o.red++;else if(e.tier==='unrated')o.unrated++;else o.green++}o.pct=o.due?Math.round(o.done/o.due*100):0;return o}
async function render(){const app=document.getElementById('app'),meds=await all('meds'),map=await latestEvents(),s=await todayStats(),st=await streak(),ps=await periodStats(),td=today();let html=`<div class="header-row"><div class="logo">Pill<span>Plan</span></div><div class="date-chip">${fmtDate()}</div></div><div class="progress-card"><div class="ring">${s.pct}%</div><div><div class="progress-title">${view==='plan'?'Dokumentation':'Heute'}</div><div class="progress-sub">${s.done} / ${s.tot} dokumentiert</div><div class="punct">Pünktlichkeit: ${s.punct}%</div><div class="streak">🔥 ${st} ${st===1?'Tag':'Tage'} in Folge</div></div></div><select class="period-select" id="period"><option value="7" ${period===7?'selected':''}>1 Woche</option><option value="14" ${period===14?'selected':''}>2 Wochen</option><option value="21" ${period===21?'selected':''}>3 Wochen</option><option value="30" ${period===30?'selected':''}>1 Monat</option></select><div class="tabs"><button class="tab ${view==='today'?'active':''}" data-v="today">💊 Heute</button><button class="tab ${view==='plan'?'active':''}" data-v="plan">📅 Plan</button><button class="tab ${view==='add'?'active':''}" data-v="add">＋ Hinzufügen</button></div><main class="content">`;
if(view==='today'){html+=`<div class="info" style="margin-bottom:12px">${esc(praise(s,st))}</div>`;for(const m of meds)for(const t of timesForDate(m,td)){const e=map[slotKey(m.id,td,t)],on=e&&e.type==='taken';html+=`<div class="card dose"><div class="dose-icon">${on?'✅':'💊'}</div><div class="grow"><div class="name">${esc(m.name)}${m.dose?' '+esc(m.dose):''}</div><div class="time">${esc(t)}</div><div class="statusline ${tierClass(e)}">${statusText(e)}</div>${m.doctorInstructions?`<div class="small">${esc(m.doctorInstructions)}</div>`:''}</div><button class="check ${on?'on':''}" data-toggle="${m.id}" data-time="${esc(t)}">${on?'✓':'○'}</button></div>`}}
if(view==='plan'){html+=`<details class="legend"><summary>Was bedeuten die Farben?</summary><div class="legend-row"><span class="sw g">✓</span> Grün – dokumentiert und pünktlich</div><div class="legend-row"><span class="sw y">!</span> Gelb – 30–44 Min. verspätet</div><div class="legend-row"><span class="sw r">!</span> Rot – 45+ Min. verspätet</div><div class="legend-row"><span class="sw n">✓</span> Hellgrau – nachgetragen, genaue Zeit unbekannt</div></details><div class="section-label">${period===7?'1 WOCHE':period===14?'2 WOCHEN':period===21?'3 WOCHEN':'1 MONAT'} · ${ps.done}/${ps.due} · ${ps.pct}%</div>`;for(const m of meds){const days=pastDays(period),has=days.some(d=>timesForDate(m,d).length);if(!has)continue;html+=`<div class="plan-med"><div class="plan-head"><div><div class="plan-name">${esc(m.name)}${m.dose?' '+esc(m.dose):''}</div><div class="small">${timesForDate(m,td).join(' · ')||'Beendet'}</div></div><div class="med-actions"><button class="mini" data-edit="${m.id}" ${m.endDate?'disabled':''}>Bearbeiten</button><button class="mini remove" data-end="${m.id}" ${m.endDate?'disabled':''}>${m.endDate?'Beendet':'Beenden'}</button></div></div><div class="days">`;for(const d of days){const cls=classifyDay(m,d,map),visual=cls==='partial'?'yellow':cls==='pre'?'':cls,mark=cls==='pre'?'·':cls?'✓':'○',dt=new Date(d+'T12:00:00');html+=`<button class="day ${visual} ${d===td?'today':''}" data-day="${d}" data-mid="${m.id}"><div>${dt.toLocaleDateString('de-DE',{weekday:'short'}).slice(0,2)}</div><strong>${dt.getDate()}</strong><div>${mark}</div></button>`}html+=`</div></div>`}}
if(view==='add')html+=`<div class="card"><div class="form-title">Medikament hinzufügen</div><input id="med-name" class="field" placeholder="Name des Medikaments"><div class="small">Einnahmezeiten pro Tag</div><div id="time-list">${timeRowsHTML(['08:00'])}</div><button id="add-time" class="btn secondary">＋ Einnahmezeit hinzufügen</button><div class="small">Ärztliche Vorgaben</div><input id="med-dose" class="field" placeholder="Dosis / Stärke, z. B. 5 mg"><textarea id="doctor-instructions" class="field" rows="3" placeholder="z. B. morgens nüchtern / nach dem Essen"></textarea><div class="small">MHD / Verfallsdatum</div><input id="med-expiry" class="field" type="date"><div class="small">Kennfarbe</div><input id="med-color" type="color" value="#2a7c74"><div class="info" style="margin-top:10px">Dein Arzt plant — PillPlan erinnert.</div><button id="add-med" class="btn primary">Medikament speichern</button></div>`;
if(view==='settings'){const x=await buildStats();html+=`<div class="card"><div class="form-title">Einstellungen</div><div class="settings-row"><strong>Statistik · 30 Tage</strong><div class="metric"><span>Dokumentierte Einnahmen</span><strong>${x.pct}%</strong></div><div class="small">Grün ${x.green} · Gelb ${x.yellow} · Rot ${x.red} · Nachgetragen ${x.unrated}</div></div><div class="settings-row"><strong>Sicherung</strong><input id="backup-file" class="field" type="file" accept="application/json,.json"><button id="import-btn" class="btn primary">Backup importieren</button><button id="export-btn" class="btn secondary">Backup exportieren</button></div></div>`}
html+=`</main><nav class="bottom-nav"><button class="nav ${view==='today'?'active':''}" data-v="today"><span class="nav-icon">💊</span>HEUTE</button><button class="nav ${view==='plan'?'active':''}" data-v="plan"><span class="nav-icon">📅</span>PLAN</button><button class="nav ${view==='add'?'active':''}" data-v="add"><span class="nav-icon">＋</span>HINZUFÜGEN</button><button class="nav ${view==='settings'?'active':''}" data-v="settings"><span class="nav-icon">⚙️</span>EINSTELLUNGEN</button></nav>`;app.innerHTML=html;bind();}
function bind(){document.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{view=b.dataset.v;render()});const p=document.getElementById('period');if(p)p.onchange=()=>{period=Number(p.value);render()};document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>toggle(Number(b.dataset.toggle),today(),b.dataset.time));document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editMed(Number(b.dataset.edit)));document.querySelectorAll('[data-end]').forEach(b=>b.onclick=()=>endMed(Number(b.dataset.end)));document.querySelectorAll('[data-day]').forEach(b=>b.onclick=async()=>{const m=await getOne('meds',Number(b.dataset.mid));if(m)chooseHistorical(m,b.dataset.day)});const at=document.getElementById('add-time');if(at)at.onclick=()=>{document.getElementById('time-list').insertAdjacentHTML('beforeend',timeRowsHTML(['12:00']));bindTimeRows()};bindTimeRows();const am=document.getElementById('add-med');if(am)am.onclick=addMed;const ex=document.getElementById('export-btn');if(ex)ex.onclick=exportBackup;const im=document.getElementById('import-btn');if(im)im.onclick=async()=>{const f=document.getElementById('backup-file').files[0];if(!f)return alert('Bitte zuerst eine Sicherungsdatei auswählen.');try{await importBackup(f);alert('Import erfolgreich')}catch(e){alert('Import fehlgeschlagen: '+e.message)}}}
window.addEventListener('error',e=>console.error('PillPlan error',e.error||e.message));
openDB().then(render).catch(e=>{document.getElementById('app').innerHTML=`<div class="card"><strong>PillPlan konnte nicht gestartet werden.</strong><div class="small">${esc(e.message)}</div></div>`});
