/* PillPlan Next consolidated runtime v2 — original v1.1 visual system + longitudinal data core */
'use strict';

const DB_NAME='pillplan-next-db', DB_VERSION=1;
let db, view='today', period=7;

function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=e=>{const d=e.target.result;if(!d.objectStoreNames.contains('meds'))d.createObjectStore('meds',{keyPath:'id'});if(!d.objectStoreNames.contains('events')){const s=d.createObjectStore('events',{keyPath:'eventId'});s.createIndex('slot','slot',{unique:false});s.createIndex('createdAt','createdAt',{unique:false});}if(!d.objectStoreNames.contains('meta'))d.createObjectStore('meta',{keyPath:'key'});};r.onsuccess=()=>{db=r.result;resolve(db)};r.onerror=()=>reject(r.error);});}
function tx(s,m='readonly'){return db.transaction(s,m).objectStore(s)}
function all(s){return new Promise((res,rej)=>{const r=tx(s).getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)})}
function getOne(s,k){return new Promise((res,rej)=>{const r=tx(s).get(k);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function put(s,o){return new Promise((res,rej)=>{const r=tx(s,'readwrite').put(o);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function clear(s){return new Promise((res,rej)=>{const r=tx(s,'readwrite').clear();r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random()}
function localDate(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function today(){return localDate()}
function addDays(ds,n){const d=new Date(ds+'T12:00:00');d.setDate(d.getDate()+n);return localDate(d)}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function fmtDate(ds=today()){return new Date(ds+'T12:00:00').toLocaleDateString('de-DE',{weekday:'long',day:'numeric',month:'long'})}
function normalizeTimes(a){return [...new Set((a||[]).filter(Boolean))].sort()}
function slotKey(mid,date,time){return `${date}_${mid}_${time}`}
function pastDays(n){const o=[];for(let i=n-1;i>=0;i--)o.push(addDays(today(),-i));return o}
function daysUntil(dateStr){if(!dateStr)return null;return Math.ceil((new Date(dateStr+'T12:00:00')-new Date(today()+'T12:00:00'))/86400000)}

async function latestEvents(){const ev=await all('events');ev.sort((a,b)=>String(a.createdAt).localeCompare(String(b.createdAt)));const m={};for(const e of ev)m[e.slot]=e;return m}
function timesForDate(m,ds){if(!m)return[];if(m.startDate&&ds<m.startDate)return[];if(m.endDate&&ds>m.endDate)return[];const h=(m.scheduleHistory||[]).filter(x=>x&&x.from&&Array.isArray(x.times)).slice().sort((a,b)=>a.from.localeCompare(b.from));let t=null;for(const x of h){if(x.from<=ds)t=x.times;else break}return normalizeTimes(t===null?(m.times||[]):t)}
function upsertSchedule(m,from,times){const h=(m.scheduleHistory||[]).slice(),i=h.findIndex(x=>x.from===from),e={from,times:normalizeTimes(times)};if(i>=0)h[i]=e;else h.push(e);h.sort((a,b)=>a.from.localeCompare(b.from));m.scheduleHistory=h}
function computeTier(time,now=new Date()){const [h,m]=time.split(':').map(Number),diff=now.getHours()*60+now.getMinutes()-(h*60+m);return diff>=45?'red':diff>=30?'yellow':'green'}
function tierClass(e){return e&&e.type==='taken'?(e.tier==='yellow'?'tier-yellow':e.tier==='red'?'tier-red':e.tier==='unrated'?'unrated':'done'):''}
function statusText(e){if(!e||e.type!=='taken')return'Offen';if(e.tier==='red')return'Dokumentiert · 45+ Min. verspätet';if(e.tier==='yellow')return'Dokumentiert · 30–44 Min. verspätet';if(e.tier==='unrated')return'Dokumentiert · Zeit nicht bewertet';return'Dokumentiert · pünktlich'}

async function toggle(mid,date,time,forced=null){const map=await latestEvents(),slot=slotKey(mid,date,time),cur=map[slot],on=!(cur&&cur.type==='taken');if(!on){const med=await getOne('meds',mid);if(!confirm(`${med?.name||'Diese Einnahme'} am ${new Date(date+'T12:00:00').toLocaleDateString('de-DE')} um ${time} wurde bereits dokumentiert.\n\nDiesen Eintrag wirklich zurücknehmen?`))return}await put('events',{eventId:uid(),slot,type:on?'taken':'undo',tier:on?(forced||computeTier(time)):'unrated',createdAt:new Date().toISOString()});await render()}
async function todayStats(){const meds=await all('meds'),map=await latestEvents();let tot=0,done=0,rated=0,onTime=0;for(const m of meds)for(const t of timesForDate(m,today())){tot++;const e=map[slotKey(m.id,today(),t)];if(e&&e.type==='taken'){done++;if(e.tier!=='unrated'){rated++;if(e.tier==='green')onTime++}}}return{tot,done,pct:tot?Math.round(done/tot*100):0,punct:rated?Math.round(onTime/rated*100):0}}
async function streak(){const meds=await all('meds'),map=await latestEvents();let s=0;for(let i=0;i<365;i++){const ds=addDays(today(),-i);let due=0,ok=true;for(const m of meds)for(const t of timesForDate(m,ds)){due++;const e=map[slotKey(m.id,ds,t)];if(!(e&&e.type==='taken'))ok=false}if(!due)continue;if(ok)s++;else break}return s}
function classifyDay(m,d,map){const ts=timesForDate(m,d);if(!ts.length)return'pre';let done=0,worst='green';for(const t of ts){const e=map[slotKey(m.id,d,t)];if(e&&e.type==='taken'){done++;if(e.tier==='red')worst='red';else if(e.tier==='yellow'&&worst!=='red')worst='yellow';else if(e.tier==='unrated'&&worst==='green')worst='unrated'}}if(!done)return'';if(done<ts.length)return'partial';return worst}
async function periodStats(){const meds=await all('meds'),map=await latestEvents();let due=0,done=0;for(const d of pastDays(period))for(const m of meds)for(const t of timesForDate(m,d)){due++;const e=map[slotKey(m.id,d,t)];if(e&&e.type==='taken')done++}return{due,done,pct:due?Math.round(done/due*100):0}}
function praise(s,st){if(!s.tot)return'';if(!s.done)return'Dein erster Check wartet.';if(s.done<s.tot)return`${s.done} von ${s.tot} dokumentiert. Du bleibst dran.`;if(st>=30)return'30 Tage in Folge. Sehr stark – diese Routine trägt.';if(st>=14)return'Zwei Wochen konsequent. Stark weitergemacht.';if(st>=7)return'Eine Woche in Folge. Stark.';if(st>=3)return`${st} Tage in Folge. Gute Routine.`;return'Alles für heute dokumentiert.'}

function timeRowsHTML(times=['08:00']){return normalizeTimes(times).map((t,i)=>`<div class="time-row"><input class="form-input med-time" type="time" value="${esc(t)}"><button type="button" class="time-remove" ${i===0&&times.length===1?'disabled':''} aria-label="Einnahmezeit entfernen">−</button></div>`).join('')}
function collectTimes(){return normalizeTimes([...document.querySelectorAll('.med-time')].map(x=>x.value))}
function bindTimeRows(){document.querySelectorAll('.time-remove').forEach(b=>b.onclick=()=>{if(document.querySelectorAll('.time-row').length>1)b.closest('.time-row').remove()})}
async function addMed(){const name=document.getElementById('med-name')?.value.trim(),times=collectTimes();if(!name)return alert('Bitte Medikamentenname eingeben.');if(!times.length)return alert('Bitte mindestens eine Einnahmezeit angeben.');await put('meds',{id:Date.now(),name,times,color:document.querySelector('.color-btn.selected')?.dataset.color||'#2a7c74',dose:(document.getElementById('med-dose')?.value||'').trim(),doctorInstructions:(document.getElementById('doctor-instructions')?.value||'').trim(),expiryDate:document.getElementById('med-expiry')?.value||'',startDate:today(),scheduleHistory:[{from:today(),times:[...times]}]});view='today';await render()}
async function editMed(id){const m=await getOne('meds',id);if(!m||m.endDate)return;const name=prompt('Medikament bearbeiten – Name',m.name);if(name===null)return;const raw=prompt('Einnahmezeiten, durch Komma getrennt',timesForDate(m,today()).join(', '));if(raw===null)return;const nt=normalizeTimes(raw.split(',').map(x=>x.trim()));if(!nt.length||nt.some(t=>!/^([01]\d|2[0-3]):[0-5]\d$/.test(t)))return alert('Bitte gültige Uhrzeiten als HH:MM eingeben.');const dose=prompt('Dosis / Stärke',m.dose||'');if(dose===null)return;const instr=prompt('Ärztliche Einnahmevorgabe',m.doctorInstructions||'');if(instr===null)return;const exp=prompt('MHD / Verfallsdatum (JJJJ-MM-TT)',m.expiryDate||'');if(exp===null)return;if(exp&&!/^\d{4}-\d{2}-\d{2}$/.test(exp))return alert('Bitte MHD als JJJJ-MM-TT eingeben.');m.name=name.trim()||m.name;m.dose=dose.trim();m.doctorInstructions=instr.trim();m.expiryDate=exp;const old=timesForDate(m,today());if(JSON.stringify(old)!==JSON.stringify(nt)){let from=today();const map=await latestEvents();if(old.some(t=>map[slotKey(m.id,today(),t)]?.type==='taken')){from=addDays(today(),1);alert('Für heute ist bereits eine Einnahme dokumentiert. Die neuen Einnahmezeiten gelten deshalb ab morgen.');}else{const ans=prompt('Ab wann sollen die neuen Einnahmezeiten gelten?\n1 = ab heute\n2 = ab morgen','1');if(ans===null)return;from=String(ans).trim()==='2'?addDays(today(),1):today();}upsertSchedule(m,from,nt);m.times=nt}await put('meds',m);await render()}
async function endMed(id){const m=await getOne('meds',id);if(!m||m.endDate)return;const map=await latestEvents(),current=timesForDate(m,today());let from=today();if(current.some(t=>map[slotKey(m.id,today(),t)]?.type==='taken')){if(!confirm(`${m.name} nach heute beenden? Die bisherige Historie bleibt vollständig erhalten.`))return;from=addDays(today(),1);}else{const ans=prompt(`${m.name} beenden – die Historie bleibt erhalten.\n1 = ab heute beenden\n2 = nach heute beenden`,'2');if(ans===null)return;from=String(ans).trim()==='1'?today():addDays(today(),1);}upsertSchedule(m,from,[]);m.endDate=addDays(from,-1);m.endedAt=new Date().toISOString();m.times=[];await put('meds',m);await render()}
async function chooseHistorical(m,date){const ts=timesForDate(m,date);if(!ts.length)return alert('Für diesen Tag war keine Einnahme geplant.');if(ts.length===1)return toggle(m.id,date,ts[0],'unrated');const ans=prompt(`Welche Einnahme ändern?\n${ts.map((t,i)=>`${i+1}: ${t}`).join('\n')}`);if(ans===null)return;const i=Number(ans)-1;if(Number.isInteger(i)&&i>=0&&i<ts.length)await toggle(m.id,date,ts[i],'unrated')}

async function exportBackup(){const payload={schema:'pillplan-next-consolidated-v2',exportedAt:new Date().toISOString(),meds:await all('meds'),events:await all('events'),meta:await all('meta')};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`PillPlan_Backup_${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function legacyTier(v){if(v===true)return'unrated';if(v===false||v==null)return null;if(typeof v==='object'){if(v.taken===false)return null;return v.tier||'unrated'}return null}
async function importBackup(file){const obj=JSON.parse(await file.text());if(obj&&Array.isArray(obj.meds)&&Array.isArray(obj.events)){await clear('meds');await clear('events');await clear('meta');for(const m of obj.meds)await put('meds',{...m,times:normalizeTimes(m.times||[])});for(const e of obj.events)await put('events',e);for(const x of obj.meta||[])await put('meta',x);await render();return}let state=obj;if(obj?.localStorage?.pillplan_v4)state=typeof obj.localStorage.pillplan_v4==='string'?JSON.parse(obj.localStorage.pillplan_v4):obj.localStorage.pillplan_v4;if(!state||!Array.isArray(state.meds)||typeof state.taken!=='object')throw new Error('Keine gültige PillPlan-Sicherung');await clear('meds');await clear('events');for(const m of state.meds)await put('meds',{id:m.id,name:m.name,times:normalizeTimes(m.times||[]),color:m.color||'#2a7c74',startDate:m.startDate||null,scheduleHistory:m.scheduleHistory||[],dose:m.dose||'',doctorInstructions:m.doctorInstructions||'',expiryDate:m.expiryDate||'',endDate:m.endDate||null});for(const [slot,val] of Object.entries(state.taken||{})){const tier=legacyTier(val);if(!tier)continue;await put('events',{eventId:uid(),slot,type:'taken',tier,createdAt:(val&&val.takenAt)||new Date().toISOString(),legacy:true})}await render()}
async function buildStats(n=30){const meds=await all('meds'),map=await latestEvents();const o={green:0,yellow:0,red:0,unrated:0,undocumented:0,due:0,done:0};for(const d of pastDays(n))for(const m of meds)for(const t of timesForDate(m,d)){o.due++;const e=map[slotKey(m.id,d,t)];if(!e||e.type!=='taken'){o.undocumented++;continue}o.done++;if(e.tier==='yellow')o.yellow++;else if(e.tier==='red')o.red++;else if(e.tier==='unrated')o.unrated++;else o.green++}o.pct=o.due?Math.round(o.done/o.due*100):0;return o}
async function shareSummary(){const meds=await all('meds'),s=await todayStats(),st=await streak();const lines=[`PillPlan – ${fmtDate()}`,`Heute: ${s.done}/${s.tot} dokumentiert (${s.pct}%)`,`Serie: ${st} ${st===1?'Tag':'Tage'}`,'',...meds.map(m=>`${m.name}${m.dose?' '+m.dose:''}: ${timesForDate(m,today()).join(', ')}`)];const text=lines.join('\n');try{if(navigator.share)await navigator.share({title:'PillPlan',text});else if(navigator.clipboard){await navigator.clipboard.writeText(text);alert('Zusammenfassung kopiert.')}else alert(text)}catch(e){if(e?.name!=='AbortError')alert('Teilen war nicht möglich.')}}
async function testNotification(){if(!('Notification'in window))return alert('Benachrichtigungen werden hier nicht unterstützt.');let p=Notification.permission;if(p==='default')p=await Notification.requestPermission();if(p!=='granted')return alert('Benachrichtigungen sind nicht freigegeben.');try{const reg=await navigator.serviceWorker?.ready;if(reg?.showNotification)await reg.showNotification('PillPlan',{body:'Test erfolgreich.',icon:'/icon.png'});else new Notification('PillPlan',{body:'Test erfolgreich.'})}catch(_e){alert('Testbenachrichtigung konnte nicht angezeigt werden.')}}

function progressRing(pct){const r=29,c=2*Math.PI*r,off=c-(Math.max(0,Math.min(100,pct))/100)*c;return `<div class="ring-wrap" aria-label="${pct}% dokumentiert"><svg width="72" height="72" viewBox="0 0 72 72" aria-hidden="true"><circle class="ring-track" cx="36" cy="36" r="29"></circle><circle class="ring-fill" cx="36" cy="36" r="29" stroke-dasharray="${c.toFixed(2)}" stroke-dashoffset="${off.toFixed(2)}"></circle></svg><div class="ring-pct">${pct}%</div></div>`}
function dayVisual(cls){if(cls==='green')return'done';if(cls==='yellow')return'tier-yellow';if(cls==='red')return'tier-red';if(cls==='unrated')return'unrated';if(cls==='partial')return'partial';return''}
function dayIcon(cls){if(cls==='pre')return'·';if(cls)return'✓';return'○'}

async function render(){
  const app=document.getElementById('app'),meds=await all('meds'),map=await latestEvents(),s=await todayStats(),st=await streak(),ps=await periodStats(),td=today();
  let html=`<header class="header"><div class="header-row"><div class="logo">Pill<span>Plan</span></div><div class="date-chip">${fmtDate()}</div></div></header>`;
  html+=`<section class="progress-card">${progressRing(s.pct)}<div class="progress-info"><div class="progress-title">${view==='plan'?'Dokumentation':'Heute'}</div><div class="progress-sub">${s.done} / ${s.tot} dokumentiert · Pünktlichkeit ${s.punct}%</div><div class="streak-row"><span class="streak-badge">🔥 ${st} ${st===1?'Tag':'Tage'} in Folge</span></div></div></section>`;
  html+=`<div class="period-selector"><select class="period-select" id="period"><option value="7" ${period===7?'selected':''}>1 Woche</option><option value="14" ${period===14?'selected':''}>2 Wochen</option><option value="21" ${period===21?'selected':''}>3 Wochen</option><option value="30" ${period===30?'selected':''}>1 Monat</option></select></div>`;
  html+=`<div class="tabs"><button class="tab ${view==='today'?'active':''}" data-v="today">💊 Heute</button><button class="tab ${view==='plan'?'active':''}" data-v="plan">📅 Plan</button><button class="tab ${view==='add'?'active':''}" data-v="add">＋ Hinzufügen</button></div><main class="content">`;

  if(view==='today'){
    const active=meds.filter(m=>timesForDate(m,td).length);
    if(s.tot&&s.done===s.tot)html+=`<div class="all-done"><div class="all-done-icon">✓</div><div class="all-done-text">Alles für heute dokumentiert</div><div class="all-done-sub">${esc(praise(s,st))}</div></div>`;
    else if(s.tot)html+=`<div class="next-banner"><div>💊</div><div><div class="next-banner-text">${esc(praise(s,st))}</div><div class="next-banner-sub">Ein Tipp genügt zur Dokumentation.</div></div></div>`;
    if(!active.length)html+=`<div class="empty"><div class="empty-icon">💊</div><div class="empty-text">Heute sind keine Medikamente geplant.</div></div>`;
    const warnings=[];for(const m of active){const d=daysUntil(m.expiryDate);if(d!==null&&d<=30)warnings.push(d<0?`${m.name}: MHD überschritten`:`${m.name}: MHD in ${d} Tagen`)}if(warnings.length)html+=`<div class="mhd-banner"><div>📅</div><div class="mhd-text">${warnings.map(esc).join('<br>')}</div></div>`;
    for(const m of active)for(const t of timesForDate(m,td)){const e=map[slotKey(m.id,td,t)],on=e&&e.type==='taken',cls=tierClass(e);html+=`<article class="dose-card ${cls}"><div class="dose-icon" style="background:${esc(m.color||'#e8f4f3')}22">${on?'✓':'💊'}</div><div class="dose-body"><div class="dose-name">${esc(m.name)}${m.dose?' '+esc(m.dose):''}</div><div class="dose-time">${esc(t)}</div><div class="dose-status ${cls||'pending'}">${statusText(e)}</div>${m.doctorInstructions?`<div class="doctor-note">${esc(m.doctorInstructions)}</div>`:''}</div><button class="check-btn ${on?'check-btn-on':'check-btn-off'}" data-toggle="${m.id}" data-time="${esc(t)}" aria-label="${on?'Dokumentation zurücknehmen':'Als eingenommen dokumentieren'}">${on?'✓':'○'}</button></article>`}
    html+=`<div class="disclaimer"><div>ℹ️</div><div class="disclaimer-text">Dein Arzt plant — PillPlan erinnert. Änderungen an Dosis oder Einnahme immer mit Arzt/Ärztin oder Apotheke klären.</div></div>`;
  }

  if(view==='plan'){
    html+=`<details class="status-legend"><summary>Was bedeuten die Farben?</summary><div class="status-legend-body"><div class="status-legend-row"><span class="status-swatch green">✓</span>Grün – dokumentiert und pünktlich</div><div class="status-legend-row"><span class="status-swatch yellow">!</span>Gelb – 30–44 Min. verspätet</div><div class="status-legend-row"><span class="status-swatch red">!</span>Rot – 45+ Min. verspätet</div><div class="status-legend-row"><span class="status-swatch neutral">✓</span>Hellgrau – nachgetragen, genaue Zeit unbekannt</div><div class="status-legend-row"><span class="status-swatch open">○</span>Nicht dokumentiert</div></div></details>`;
    html+=`<div class="section-label">${period===7?'1 Woche':period===14?'2 Wochen':period===21?'3 Wochen':'1 Monat'} · ${ps.done}/${ps.due} · ${ps.pct}% dokumentiert</div>`;
    const days=pastDays(period);
    for(const m of meds){const has=days.some(d=>timesForDate(m,d).length);if(!has)continue;const current=timesForDate(m,td);html+=`<section class="plan-med"><div class="plan-med-header"><div><div class="plan-med-name"><span class="color-dot" style="background:${esc(m.color||'#2a7c74')}"></span>${esc(m.name)}${m.dose?' '+esc(m.dose):''}</div><div class="plan-med-time">${m.endDate?`Beendet am ${new Date(m.endDate+'T12:00:00').toLocaleDateString('de-DE')}`:(current.length?current.join(' · '):'Aktuell keine Einnahme')}</div></div><div class="plan-actions"><button class="icon-action" data-edit="${m.id}" ${m.endDate?'disabled':''} aria-label="Bearbeiten">✎</button><button class="icon-action danger" data-end="${m.id}" ${m.endDate?'disabled':''} aria-label="${m.endDate?'Beendet':'Medikament beenden'}">${m.endDate?'✓':'×'}</button></div></div><div class="day-grid">`;
      for(const d of days){const cls=classifyDay(m,d,map),dt=new Date(d+'T12:00:00'),visual=dayVisual(cls);html+=`<button class="day-cell ${visual} ${d===td?'today':''}" data-day="${d}" data-mid="${m.id}"><span class="day-wd">${dt.toLocaleDateString('de-DE',{weekday:'short'}).slice(0,2)}</span><span class="day-num">${dt.getDate()}</span><span class="day-ico">${dayIcon(cls)}</span></button>`}html+=`</div></section>`;
    }
  }

  if(view==='add'){
    html+=`<section class="form-card"><div class="form-title">Medikament hinzufügen</div><label class="form-label" for="med-name">Medikament</label><input id="med-name" class="form-input" placeholder="Name des Medikaments"><label class="form-label">Einnahmezeit</label><div id="time-list">${timeRowsHTML(['08:00'])}</div><button type="button" id="add-time" class="secondary-action">＋ Weitere Einnahmezeit</button><label class="form-label" for="med-dose">Dosis / Stärke</label><input id="med-dose" class="form-input" placeholder="z. B. 5 mg"><label class="form-label" for="doctor-instructions">Ärztliche Vorgabe</label><textarea id="doctor-instructions" class="form-input" rows="3" placeholder="z. B. morgens nüchtern / nach dem Essen"></textarea><label class="form-label" for="med-expiry">MHD / Verfallsdatum</label><input id="med-expiry" class="form-input" type="date"><label class="form-label">Kennfarbe</label><div class="colors-row">${['#2a7c74','#c0392b','#b08d57','#3f6ea8','#7a5ca8','#6c7a4d'].map((c,i)=>`<button type="button" class="color-btn ${i===0?'selected':''}" data-color="${c}" style="background:${c}" aria-label="Kennfarbe wählen"></button>`).join('')}</div><div class="disclaimer"><div>ℹ️</div><div class="disclaimer-text">Dein Arzt plant — PillPlan erinnert. Änderungen an Dosis oder Einnahme immer mit Arzt/Ärztin oder Apotheke klären.</div></div><button id="add-med" class="primary-action">Medikament speichern</button></section>`;
  }

  if(view==='settings'){
    const stats=await buildStats(30);html+=`<section class="settings-card"><div class="form-title">Einstellungen</div><div class="settings-row"><div><div class="settings-row-label">Daten</div><div class="settings-row-sub">Lokale Speicherung auf diesem Gerät</div></div><span>IndexedDB</span></div><div class="settings-block"><div class="settings-row-label">Sicherung</div><input id="backup-file" class="form-input" type="file" accept="application/json,.json"><button id="import-btn" class="primary-action">Backup importieren</button><button id="export-btn" class="secondary-action full">Backup exportieren</button></div></section>`;
    html+=`<section class="stats-card"><div class="section-label">Letzte 30 Tage</div><div class="stats-hero"><strong>${stats.pct}%</strong><span>Dokumentierte Einnahmen</span></div><div class="stats-grid"><div><span class="status-swatch green">✓</span><b>${stats.green}</b><small>Pünktlich</small></div><div><span class="status-swatch yellow">!</span><b>${stats.yellow}</b><small>30–44 Min.</small></div><div><span class="status-swatch red">!</span><b>${stats.red}</b><small>45+ Min.</small></div><div><span class="status-swatch neutral">✓</span><b>${stats.unrated}</b><small>Nachgetragen</small></div></div></section>`;
    html+=`<section class="settings-card"><div class="settings-row"><div><div class="settings-row-label">Teilen</div><div class="settings-row-sub">Kurze Zusammenfassung teilen oder kopieren</div></div><button id="share-btn" class="row-action">Teilen</button></div><div class="settings-row"><div><div class="settings-row-label">Drucken</div><div class="settings-row-sub">Aktuelle Ansicht drucken</div></div><button id="print-btn" class="row-action">Drucken</button></div><div class="settings-row"><div><div class="settings-row-label">Benachrichtigung testen</div><div class="settings-row-sub">Nur Funktionstest – keine verlässliche Hintergrundplanung</div></div><button id="notify-btn" class="row-action">Test</button></div></section>`;
  }

  html+=`</main><nav class="bottom-nav"><button class="nav ${view==='today'?'active':''}" data-v="today"><span class="nav-icon">💊</span><span>HEUTE</span></button><button class="nav ${view==='plan'?'active':''}" data-v="plan"><span class="nav-icon">📅</span><span>PLAN</span></button><button class="nav ${view==='add'?'active':''}" data-v="add"><span class="nav-icon">＋</span><span>HINZUFÜGEN</span></button><button class="nav ${view==='settings'?'active':''}" data-v="settings"><span class="nav-icon">⚙️</span><span>EINSTELLUNGEN</span></button></nav>`;
  app.innerHTML=html;bindUI(meds,td);
}

function bindUI(meds,td){
  document.querySelectorAll('[data-v]').forEach(b=>b.onclick=async()=>{view=b.dataset.v;await render()});
  const p=document.getElementById('period');if(p)p.onchange=async()=>{period=Number(p.value);await render()};
  document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>toggle(Number(b.dataset.toggle),td,b.dataset.time));
  document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editMed(Number(b.dataset.edit)));
  document.querySelectorAll('[data-end]').forEach(b=>b.onclick=()=>endMed(Number(b.dataset.end)));
  document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{const m=meds.find(x=>x.id===Number(b.dataset.mid));if(m)chooseHistorical(m,b.dataset.day)});
  document.querySelectorAll('.color-btn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.color-btn').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')});
  const addTime=document.getElementById('add-time');if(addTime){addTime.onclick=()=>{const wrap=document.getElementById('time-list'),row=document.createElement('div');row.className='time-row';row.innerHTML='<input class="form-input med-time" type="time" value="12:00"><button type="button" class="time-remove" aria-label="Einnahmezeit entfernen">−</button>';wrap.appendChild(row);bindTimeRows()};bindTimeRows()}
  const add=document.getElementById('add-med');if(add)add.onclick=addMed;
  const imp=document.getElementById('import-btn');if(imp)imp.onclick=async()=>{const f=document.getElementById('backup-file')?.files?.[0];if(!f)return alert('Bitte zuerst eine Sicherungsdatei auswählen.');try{await importBackup(f);alert('Import erfolgreich.')}catch(e){alert('Import fehlgeschlagen: '+e.message)}};
  const exp=document.getElementById('export-btn');if(exp)exp.onclick=exportBackup;
  const sh=document.getElementById('share-btn');if(sh)sh.onclick=shareSummary;
  const pr=document.getElementById('print-btn');if(pr)pr.onclick=()=>window.print();
  const no=document.getElementById('notify-btn');if(no)no.onclick=testNotification;
}

openDB().then(render).catch(e=>{document.getElementById('app').innerHTML=`<div class="fatal-card"><strong>PillPlan konnte nicht gestartet werden.</strong><div>${esc(e?.message||e)}</div></div>`});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/pillplan-next/sw.js',{scope:'/pillplan-next/'}).catch(()=>{}));
